import api from './client';
export const getEntities = () => api.get('/reports/entities').then(r => r.data);
export const getFieldOptions = (entity, field) => api.get('/reports/field-options', { params: { entity, field } }).then(r => r.data);
export const getReports = () => api.get('/reports').then(r => r.data);
export const createReport = (data) => api.post('/reports', data).then(r => r.data);
export const updateReport = (id, data) => api.put(`/reports/${id}`, data).then(r => r.data);
export const deleteReport = (id) => api.delete(`/reports/${id}`).then(r => r.data);
export const runReport = (id) => api.get(`/reports/${id}/run`).then(r => r.data);
export const getMyDashboard = () => api.get('/reports/dashboard/my').then(r => r.data);
export const getUserDashboard = (userId) => api.get(`/reports/dashboard/user/${userId}`).then(r => r.data);
